export const routes = {
  home: "/",
  auth: {
    login: "/login",
    register: "/register",
    forgotPassword: "/forgot-password",
  },
  dashboard: {
    root: "/dashboard",
    clients: "/dashboard/clients",
    vendors: "/dashboard/vendors",
    contacts: "/dashboard/contacts",
    sites: "/dashboard/sites",
    quotations: "/dashboard/quotations",
    invoices: "/dashboard/invoices",
    purchaseOrders: "/dashboard/purchase-orders",
    jobs: "/dashboard/jobs",
    jobFormFill: (jobId: number | string, formId: number | string, job_form_id: number | string) =>
      `/dashboard/jobs/${jobId}/form?formId=${formId}&job_form_id=${job_form_id}`,
    qrCodes: "/dashboard/qr-codes",
    projects: "/dashboard/projects",
    groups: "/dashboard/groups",
    items: "/dashboard/items",
    compositeItems: "/dashboard/composite-items",
    materialRequests: "/dashboard/material-requests",
    dispatches: "/dashboard/dispatches",
    returnToStock: "/dashboard/return-to-stock",
    settings: "/dashboard/settings",
    settingsPinStatus: "/dashboard/settings/pin-status",
    settingsJobStatus: "/dashboard/settings/job-status",
    settingsMaterialStatus: "/dashboard/settings/material-status",
    settingsTags: "/dashboard/settings/tag",
    settingsProjectTypes: "/dashboard/settings/project-type",
    settingsInstallationTypes: "/dashboard/settings/installation-type",
    settingsVendorTypes: "/dashboard/settings/vendor-type",
    settingsCustomization: "/dashboard/settings/customization",
    settingsUsers: "/dashboard/settings/users",
    settingsPersonalProfile: "/dashboard/settings/personal-profile",
    settingsCompanySettings: "/dashboard/settings/company-settings",
    settingsModules: "/dashboard/settings/modules",
    settingsProjectForms: "/dashboard/settings/project-type-forms",
    projectJobsForms: "/dashboard/projects/[id]/job-forms"
  },

} as const;
