export const routes = {
  home: "/",
  auth: {
    login: "/login",
    signUp: "/sign-up",
    forgotPassword: "/forgot-password",
  },
  dashboard: {
    root: "/home",
    clients: "/clients",
    vendors: "/vendors",
    contacts: "/contacts",
    sites: "/sites",
    quotations: "/quotations",
    quotationService: "/quotations?quote_category=servicequote",
    quotationProject: "/quotations?quote_category=projectquote",
    invoices: "/invoices",
    purchaseOrders: "/purchase-orders",
    jobs: "/jobs",
    jobFormFill: (jobId: number | string, formId: number | string, job_form_id: number | string) =>
      `/jobs/${jobId}/form?formId=${formId}&job_form_id=${job_form_id}`,
    qrCodes: "/qr-codes",
    projects: "/projects",
    groups: "/groups",
    items: "/items",
    compositeItems: "/composite-items",
    materialRequests: "/material-requests",
    dispatches: "/dispatches",
    returnToStock: "/return-to-stock",
    settings: "/settings",
    settingsPinStatus: "/settings/pin-status",
    settingsProjectStatus: "/settings/project-status",
    settingsJobStatus: "/settings/job-status",
    settingsMaterialStatus: "/settings/material-status",
    settingsTags: "/settings/tag",
    settingsProjectTypes: "/settings/project-type",
    settingsInstallationTypes: "/settings/installation-type",
    settingsVendorTypes: "/settings/vendor-type",
    settingsUnitTypes: "/settings/unit-type",
    settingsChecklistTypes: "/settings/checklist-type",
    settingsCustomization: "/settings/customization",
    settingsUsers: "/settings/users",
    settingsPersonalProfile: "/settings/personal-profile",
    settingsCompanySettings: "/settings/company-settings",
    settingsModules: "/settings/modules",
    settingsProjectForms: "/settings/project-type-forms",
    settingsIntegrations: "/settings/integrations",
    settingsZohoCallback: "/settings/integrations/zoho/callback",
    settingsZohoKeyMapping: "/settings/integrations/zoho/key-mapping",
    settingsZohoConnection: "/settings/integrations/zoho/connection",
    settingsZohoWebhookSetup: "/settings/integrations/zoho/webhook-setup",
    projectJobsForms: "/projects/[id]/job-forms",
    settingsTitle: "/settings/title-settings",
  },
} as const;
