export interface Currency {
  countryCode: string;
  value: string;
  label: string;
  symbol: string;
}

export const currencyList: Currency[] = [
  // Americas
  { countryCode: "US", value: "USD", label: "US Dollar", symbol: "$" },
  { countryCode: "CA", value: "CAD", label: "Canadian Dollar", symbol: "$" },
  { countryCode: "MX", value: "MXN", label: "Mexican Peso", symbol: "$" },
  { countryCode: "BR", value: "BRL", label: "Brazilian Real", symbol: "R$" },
  { countryCode: "AR", value: "ARS", label: "Argentine Peso", symbol: "$" },
  { countryCode: "CL", value: "CLP", label: "Chilean Peso", symbol: "$" },
  { countryCode: "CO", value: "COP", label: "Colombian Peso", symbol: "$" },
  { countryCode: "PE", value: "PEN", label: "Peruvian Sol", symbol: "S/" },
  { countryCode: "UY", value: "UYU", label: "Uruguayan Peso", symbol: "$" },
  { countryCode: "VE", value: "VES", label: "Venezuelan Bolívar", symbol: "Bs." },
  { countryCode: "CR", value: "CRC", label: "Costa Rican Colón", symbol: "₡" },
  { countryCode: "GT", value: "GTQ", label: "Guatemalan Quetzal", symbol: "Q" },
  { countryCode: "PA", value: "PAB", label: "Panamanian Balboa", symbol: "B/." },
  { countryCode: "DO", value: "DOP", label: "Dominican Peso", symbol: "$" },
  { countryCode: "JM", value: "JMD", label: "Jamaican Dollar", symbol: "$" },
  { countryCode: "TT", value: "TTD", label: "Trinidad & Tobago Dollar", symbol: "$" },
  { countryCode: "BS", value: "BSD", label: "Bahamian Dollar", symbol: "$" },
  { countryCode: "BB", value: "BBD", label: "Barbadian Dollar", symbol: "$" },
  { countryCode: "BZ", value: "BZD", label: "Belize Dollar", symbol: "$" },
  { countryCode: "HN", value: "HNL", label: "Honduran Lempira", symbol: "L" },
  { countryCode: "NI", value: "NIO", label: "Nicaraguan Córdoba", symbol: "C$" },
  { countryCode: "PY", value: "PYG", label: "Paraguayan Guaraní", symbol: "₲" },
  { countryCode: "BO", value: "BOB", label: "Bolivian Boliviano", symbol: "Bs." },
  { countryCode: "SV", value: "USD", label: "US Dollar (El Salvador)", symbol: "$" },

  // Europe
  { countryCode: "EU", value: "EUR", label: "Euro", symbol: "€" },
  { countryCode: "GB", value: "GBP", label: "British Pound", symbol: "£" },
  { countryCode: "CH", value: "CHF", label: "Swiss Franc", symbol: "CHF" },
  { countryCode: "SE", value: "SEK", label: "Swedish Krona", symbol: "kr" },
  { countryCode: "NO", value: "NOK", label: "Norwegian Krone", symbol: "kr" },
  { countryCode: "DK", value: "DKK", label: "Danish Krone", symbol: "kr" },
  { countryCode: "PL", value: "PLN", label: "Polish Złoty", symbol: "zł" },
  { countryCode: "CZ", value: "CZK", label: "Czech Koruna", symbol: "Kč" },
  { countryCode: "HU", value: "HUF", label: "Hungarian Forint", symbol: "Ft" },
  { countryCode: "RO", value: "RON", label: "Romanian Leu", symbol: "lei" },
  { countryCode: "BG", value: "BGN", label: "Bulgarian Lev", symbol: "лв" },
  { countryCode: "HR", value: "EUR", label: "Euro (Croatia)", symbol: "€" },
  { countryCode: "RS", value: "RSD", label: "Serbian Dinar", symbol: "дин" },
  { countryCode: "UA", value: "UAH", label: "Ukrainian Hryvnia", symbol: "₴" },
  { countryCode: "TR", value: "TRY", label: "Turkish Lira", symbol: "₺" },
  { countryCode: "RU", value: "RUB", label: "Russian Ruble", symbol: "₽" },
  { countryCode: "IS", value: "ISK", label: "Icelandic Króna", symbol: "kr" },
  { countryCode: "BY", value: "BYN", label: "Belarusian Ruble", symbol: "Br" },
  { countryCode: "MD", value: "MDL", label: "Moldovan Leu", symbol: "L" },
  { countryCode: "AL", value: "ALL", label: "Albanian Lek", symbol: "L" },
  { countryCode: "MK", value: "MKD", label: "Macedonian Denar", symbol: "ден" },
  { countryCode: "BA", value: "BAM", label: "Bosnia-Herzegovina Mark", symbol: "KM" },

  // Asia
  { countryCode: "IN", value: "INR", label: "Indian Rupee", symbol: "₹" },
  { countryCode: "CN", value: "CNY", label: "Chinese Yuan", symbol: "¥" },
  { countryCode: "JP", value: "JPY", label: "Japanese Yen", symbol: "¥" },
  { countryCode: "KR", value: "KRW", label: "South Korean Won", symbol: "₩" },
  { countryCode: "HK", value: "HKD", label: "Hong Kong Dollar", symbol: "$" },
  { countryCode: "SG", value: "SGD", label: "Singapore Dollar", symbol: "$" },
  { countryCode: "TH", value: "THB", label: "Thai Baht", symbol: "฿" },
  { countryCode: "MY", value: "MYR", label: "Malaysian Ringgit", symbol: "RM" },
  { countryCode: "ID", value: "IDR", label: "Indonesian Rupiah", symbol: "Rp" },
  { countryCode: "PH", value: "PHP", label: "Philippine Peso", symbol: "₱" },
  { countryCode: "VN", value: "VND", label: "Vietnamese Dong", symbol: "₫" },
  { countryCode: "BD", value: "BDT", label: "Bangladeshi Taka", symbol: "৳" },
  { countryCode: "PK", value: "PKR", label: "Pakistani Rupee", symbol: "₨" },
  { countryCode: "LK", value: "LKR", label: "Sri Lankan Rupee", symbol: "Rs" },
  { countryCode: "NP", value: "NPR", label: "Nepalese Rupee", symbol: "Rs" },
  { countryCode: "MM", value: "MMK", label: "Myanmar Kyat", symbol: "K" },
  { countryCode: "KH", value: "KHR", label: "Cambodian Riel", symbol: "៛" },
  { countryCode: "LA", value: "LAK", label: "Lao Kip", symbol: "₭" },
  { countryCode: "MN", value: "MNT", label: "Mongolian Tugrik", symbol: "₮" },
  { countryCode: "BN", value: "BND", label: "Brunei Dollar", symbol: "$" },
  { countryCode: "MO", value: "MOP", label: "Macanese Pataca", symbol: "P" },
  { countryCode: "TW", value: "TWD", label: "New Taiwan Dollar", symbol: "$" },
  { countryCode: "KZ", value: "KZT", label: "Kazakhstani Tenge", symbol: "₸" },
  { countryCode: "UZ", value: "UZS", label: "Uzbekistani Som", symbol: "so'm" },
  { countryCode: "KG", value: "KGS", label: "Kyrgyzstani Som", symbol: "с" },
  { countryCode: "TJ", value: "TJS", label: "Tajikistani Somoni", symbol: "ЅМ" },
  { countryCode: "TM", value: "TMT", label: "Turkmenistani Manat", symbol: "m" },
  { countryCode: "AF", value: "AFN", label: "Afghan Afghani", symbol: "؋" },
  { countryCode: "BT", value: "BTN", label: "Bhutanese Ngultrum", symbol: "Nu." },
  { countryCode: "MV", value: "MVR", label: "Maldivian Rufiyaa", symbol: "Rf" },

  // Middle East
  { countryCode: "AE", value: "AED", label: "UAE Dirham", symbol: "د.إ" },
  { countryCode: "SA", value: "SAR", label: "Saudi Riyal", symbol: "﷼" },
  { countryCode: "IL", value: "ILS", label: "Israeli Shekel", symbol: "₪" },
  { countryCode: "EG", value: "EGP", label: "Egyptian Pound", symbol: "£" },
  { countryCode: "QA", value: "QAR", label: "Qatari Riyal", symbol: "﷼" },
  { countryCode: "KW", value: "KWD", label: "Kuwaiti Dinar", symbol: "د.ك" },
  { countryCode: "BH", value: "BHD", label: "Bahraini Dinar", symbol: "د.ب" },
  { countryCode: "OM", value: "OMR", label: "Omani Rial", symbol: "﷼" },
  { countryCode: "JO", value: "JOD", label: "Jordanian Dinar", symbol: "د.ا" },
  { countryCode: "LB", value: "LBP", label: "Lebanese Pound", symbol: "ل.ل" },
  { countryCode: "SY", value: "SYP", label: "Syrian Pound", symbol: "£" },
  { countryCode: "IQ", value: "IQD", label: "Iraqi Dinar", symbol: "ع.د" },
  { countryCode: "IR", value: "IRR", label: "Iranian Rial", symbol: "﷼" },
  { countryCode: "YE", value: "YER", label: "Yemeni Rial", symbol: "﷼" },
  { countryCode: "PS", value: "ILS", label: "Israeli Shekel (Palestine)", symbol: "₪" },
  { countryCode: "AM", value: "AMD", label: "Armenian Dram", symbol: "֏" },
  { countryCode: "AZ", value: "AZN", label: "Azerbaijani Manat", symbol: "₼" },
  { countryCode: "GE", value: "GEL", label: "Georgian Lari", symbol: "₾" },
  { countryCode: "CY", value: "EUR", label: "Euro (Cyprus)", symbol: "€" },

  // Africa
  { countryCode: "ZA", value: "ZAR", label: "South African Rand", symbol: "R" },
  { countryCode: "NG", value: "NGN", label: "Nigerian Naira", symbol: "₦" },
  { countryCode: "KE", value: "KES", label: "Kenyan Shilling", symbol: "KSh" },
  { countryCode: "GH", value: "GHS", label: "Ghanaian Cedi", symbol: "₵" },
  { countryCode: "ET", value: "ETB", label: "Ethiopian Birr", symbol: "Br" },
  { countryCode: "TZ", value: "TZS", label: "Tanzanian Shilling", symbol: "TSh" },
  { countryCode: "UG", value: "UGX", label: "Ugandan Shilling", symbol: "USh" },
  { countryCode: "DZ", value: "DZD", label: "Algerian Dinar", symbol: "د.ج" },
  { countryCode: "MA", value: "MAD", label: "Moroccan Dirham", symbol: "د.م." },
  { countryCode: "TN", value: "TND", label: "Tunisian Dinar", symbol: "د.ت" },
  { countryCode: "LY", value: "LYD", label: "Libyan Dinar", symbol: "ل.د" },
  { countryCode: "SD", value: "SDG", label: "Sudanese Pound", symbol: "ج.س." },
  { countryCode: "AO", value: "AOA", label: "Angolan Kwanza", symbol: "Kz" },
  { countryCode: "ZM", value: "ZMW", label: "Zambian Kwacha", symbol: "ZK" },
  { countryCode: "ZW", value: "ZWL", label: "Zimbabwean Dollar", symbol: "$" },
  { countryCode: "BW", value: "BWP", label: "Botswana Pula", symbol: "P" },
  { countryCode: "MZ", value: "MZN", label: "Mozambican Metical", symbol: "MT" },
  { countryCode: "MU", value: "MUR", label: "Mauritian Rupee", symbol: "₨" },
  { countryCode: "RW", value: "RWF", label: "Rwandan Franc", symbol: "Fr" },
  { countryCode: "SC", value: "SCR", label: "Seychellois Rupee", symbol: "₨" },
  { countryCode: "SN", value: "XOF", label: "West African CFA Franc", symbol: "Fr" },
  { countryCode: "CI", value: "XOF", label: "West African CFA Franc (Ivory Coast)", symbol: "Fr" },
  { countryCode: "CM", value: "XAF", label: "Central African CFA Franc", symbol: "Fr" },
  { countryCode: "CD", value: "CDF", label: "Congolese Franc", symbol: "Fr" },
  { countryCode: "MG", value: "MGA", label: "Malagasy Ariary", symbol: "Ar" },
  { countryCode: "MW", value: "MWK", label: "Malawian Kwacha", symbol: "MK" },
  { countryCode: "NA", value: "NAD", label: "Namibian Dollar", symbol: "$" },
  { countryCode: "LS", value: "LSL", label: "Lesotho Loti", symbol: "L" },
  { countryCode: "SZ", value: "SZL", label: "Swazi Lilangeni", symbol: "L" },
  { countryCode: "GM", value: "GMD", label: "Gambian Dalasi", symbol: "D" },
  { countryCode: "SL", value: "SLL", label: "Sierra Leonean Leone", symbol: "Le" },
  { countryCode: "LR", value: "LRD", label: "Liberian Dollar", symbol: "$" },
  { countryCode: "BF", value: "XOF", label: "West African CFA Franc (Burkina Faso)", symbol: "Fr" },
  { countryCode: "ML", value: "XOF", label: "West African CFA Franc (Mali)", symbol: "Fr" },
  { countryCode: "NE", value: "XOF", label: "West African CFA Franc (Niger)", symbol: "Fr" },
  { countryCode: "TD", value: "XAF", label: "Central African CFA Franc (Chad)", symbol: "Fr" },
  { countryCode: "BI", value: "BIF", label: "Burundian Franc", symbol: "Fr" },
  { countryCode: "DJ", value: "DJF", label: "Djiboutian Franc", symbol: "Fr" },
  { countryCode: "ER", value: "ERN", label: "Eritrean Nakfa", symbol: "Nfk" },
  { countryCode: "SO", value: "SOS", label: "Somali Shilling", symbol: "Sh" },
  { countryCode: "MR", value: "MRU", label: "Mauritanian Ouguiya", symbol: "UM" },
  { countryCode: "CV", value: "CVE", label: "Cape Verdean Escudo", symbol: "$" },
  { countryCode: "ST", value: "STN", label: "São Tomé and Príncipe Dobra", symbol: "Db" },
  { countryCode: "KM", value: "KMF", label: "Comorian Franc", symbol: "Fr" },

  // Oceania
  { countryCode: "AU", value: "AUD", label: "Australian Dollar", symbol: "$" },
  { countryCode: "NZ", value: "NZD", label: "New Zealand Dollar", symbol: "$" },
  { countryCode: "FJ", value: "FJD", label: "Fijian Dollar", symbol: "$" },
  { countryCode: "PG", value: "PGK", label: "Papua New Guinean Kina", symbol: "K" },
  { countryCode: "SB", value: "SBD", label: "Solomon Islands Dollar", symbol: "$" },
  { countryCode: "VU", value: "VUV", label: "Vanuatu Vatu", symbol: "Vt" },
  { countryCode: "WS", value: "WST", label: "Samoan Tala", symbol: "T" },
  { countryCode: "TO", value: "TOP", label: "Tongan Paʻanga", symbol: "T$" },
  { countryCode: "NC", value: "XPF", label: "CFP Franc", symbol: "Fr" },
  { countryCode: "PF", value: "XPF", label: "CFP Franc (French Polynesia)", symbol: "Fr" },

  // Special & Cryptocurrencies (Optional)
  { countryCode: "XAU", value: "XAU", label: "Gold (Troy Ounce)", symbol: "oz" },
  { countryCode: "XAG", value: "XAG", label: "Silver (Troy Ounce)", symbol: "oz" },
  { countryCode: "BTC", value: "BTC", label: "Bitcoin", symbol: "₿" },
  { countryCode: "ETH", value: "ETH", label: "Ethereum", symbol: "Ξ" },
];
